// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package stubs;

public interface APIResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.APIResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 1;</code>
   * @return The responseMessage.
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 1;</code>
   * @return The bytes for responseMessage.
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();

  /**
   * <code>int32 messageCode = 2;</code>
   * @return The messageCode.
   */
  int getMessageCode();
}
