// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package stubs;

public interface OrderIDOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.OrderID)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 orderNumber = 1;</code>
   * @return The orderNumber.
   */
  int getOrderNumber();
}
