// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package stubs;

public interface OrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Order)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int64 customerTable = 2;</code>
   * @return The customerTable.
   */
  long getCustomerTable();

  /**
   * <code>string observations = 3;</code>
   * @return The observations.
   */
  java.lang.String getObservations();
  /**
   * <code>string observations = 3;</code>
   * @return The bytes for observations.
   */
  com.google.protobuf.ByteString
      getObservationsBytes();

  /**
   * <code>int64 quantidade = 4;</code>
   * @return The quantidade.
   */
  long getQuantidade();
}
